# Generated by Django 6.0.4 on 2026-04-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='khatauser',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
